version: '3.8'

services: 
  nginx:
    image: nginx
    ports:
      - 80:80
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - ./src:/var/www/html

configs:
  nginx_config:
    file: ./nginx/default.conf