services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    secrets:
      - mysql_root_password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

secrets:
  mysql_root_password:
    file: db/mysql_root_password.txt